<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hx</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(/\*\*|\{\s*$)</string>
	<key>foldingStopMarker</key>
	<string>(\*\*/|^\s*\})</string>
	<key>name</key>
	<string>haXe</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#(if|else|elseif|end)\b</string>
			<key>name</key>
			<string>keyword.preprocessor.macro.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(flash.)?\b(Accessibility|Boot|Button|Camera|Color|ContextMenu|ContextMenuItem|ExtendedKey|Key|Lib|LoadVars|LocalConnection|Microphone|Mouse|MovieClip|MovieClipLoader|NetConnection|NetStream|PrintJob|Selection|SelectionListener|SharedObject|Sound|Stage|System|TextField|TextFormat|TextSnapshot|Video|XMLRequest|XMLSocket)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(flash.display.)?\b(BitmapData)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash.display</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(flash.external.)?\b(ExternalInterface)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash.external</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BevelFilter|BitmapFilter|BlurFilter|ColorMatrixFilter|ConvolutionFilter|DisplacementMapFilter|DropShadowFilter|GlowFilter|GradientBevelFilter|GradientGlowFilter)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash.filters</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(flash.geom.)?\b(ColorTransform|Matrix|Point|Rectangle|Transform)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash.geom</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FileReference|FileReferenceList)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash.net</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(flash.system.)?\b(Capabilities|IME|Security|LoaderContext|SecurityDomain|ApplicationDomain)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash.system</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(StyleSheet|TextRenderer)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash.text</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Boot|Error|Lib|Vector)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Accessibility|AccessibilityImplementation|AccessibilityProperties)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.accessibility</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(flash.display.)?\b(AVM1Movie|ActionScriptVersion|Bitmap|BitmapData|BitmapDataChannel|BlendMode|CapsStyle|DisplayObject|DisplayObjectContainer|FrameLabel|GradientType|Graphics|GraphicsBitmapFill|GraphicsEndFill|GraphicsGradientFill|GraphicsPath|GraphicsPathCommand|GraphicsPathWinding|GraphicsShaderFill|GraphicsSolidFill|GraphicsStroke|GraphicsTrianglePath|IBitmapDrawable|IGraphicsData|IGraphicsFill|IGraphicsPath|IGraphicsStroke|InteractiveObject|InterpolationMethod|JointStyle|LineScaleMode|Loader|LoaderInfo|MorphShape|MovieClip|PixelSnapping|SWFVersion|Scene|Shader|ShaderData|ShaderInput|ShaderJob|ShaderParameter|ShaderParameterType|ShaderPrecision|Shape|SimpleButton|SpreadMethod|Sprite|Stage|StageAlign|StageDisplayStage|StageQuality|StageScaleMode|TriangleCulling)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.display</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(EOFError|IOError|IllegalOperationError|InvalidSWFError|MemoryError|ScriptTimeoutError|StackOverflowError)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.errors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ActivityEvent|AsyncErrorEvent|ContextMenuEvent|DataEvent|ErrorEvent|Event|EventDispatcher|EventPhase|FocusEvent|FullScreenEvent|HTTPStatusEvent|IEventDispatcher|IMEEvent|IOErrorEvent|KeyboardEvent|MouseEvent|NetFilterEvent|NetStatusEvent|ProgressEvent|SamplesCallbackEvent|SecurityErrorEvent|ShaderEvent|StatusEvent|SyncEvent|TextEvent|TimerEvent|WeakFunctionClosure|WeakMethodClosure)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.events</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ExternalInterface)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.external</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BevelFilter|BitmapFilter|BitmapFilterQuality|BitmapFilterType|BlurFilter|ColorMatrixFilter|ConvolutionFilter|DisplacementMapFilter|DisplacementMapFilterMode|DropShadowFilter|GlowFilter|GradientBevelFilter|GradientGlowFilter|ShaderFilter)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.filters</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ColorTransform|Matrix|Matrix3D|Orientation3D|PerspectiveProjection|Point|Rectangle|Transform|Utils3D|Vector3D)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.geom</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Camera|ID3Info|Microphone|Sound|SoundChannel|SoundCodec|SoundLoaderContext|SoundMixer|SoundTransform|Video)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.media</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(DynamicPropertyOutput|FileFilter|FileReference|FileReferenceList|IDynamicPropertyOutput|IDynamicPropertyWriter|LocalConnection|NetConnection|NetStream|NetStreamInfo|NetStreamPlayOptions|NetStreamPlayTransitions|ObjectEncoding|Responder|SharedObject|SharedObjectFlushStatus|Socket|URLLoader|URLLoaderDataFormat|URLRequest|URLRequestHeader|URLRequestMethod|URLStream|URLVariables|XMLSocket)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.net</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(PrintJob|PrintJobOptions|PrintJobOrientation)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.printing</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Api|DeleteObjectSample|NewObjectSample|Sample|StackFrame)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.sampler</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ApplicationDomain|Capabilities|FSCommand|IME|IMEConversionMode|JPEGLoaderContext|LoaderContext|Security|SecurityDomain|SecurityPanel|System)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.system</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(AntiAliasType|CSMSettings|Font|FontStyle|FontType|GridFitType|StaticText|StyleSheet|TextColorType|TextDisplayMode|TextExtent|TextField|TextFieldAutoSize|TextFieldType|TextFormat|TextFormatAlign|TextFormatDisplay|TextLineMetrics|TextRenderer|TextRun|TextSnapshot)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.text</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BreakOpportunity|ContentElement|DigitCase|DigitWidth|EastAsianJustifier|ElementFormat|FontDescription|FontLookup|FontMetrics|FontPosture|FontWeight|GlyphRotation|GraphicElement|GroupElement|JustificationStyle|Kerning|LigatureLevel|LineJustification|SpaceJustifier|TabAlignment|TabStop|TextBaseline|TextBlock|TextElement|TextJustifier|TextLine|TextLineCreationResult|TextLineMirrorRegion|TextLineValidity|TextRotation|TypographicCase)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.text.engine</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Trace)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.trace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ContextMenu|ContextMenuBuiltInItems|ContextMenuClipboardItems|ContextMenuItem|KeyLocation|Keyboard|Mouse|MouseCursor)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.ui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ByteArray|Dictionary|Endian|IDataInput|IDataOutput|IExternalizable|Namespace|ObjectInput|ObjectOutput|Proxy|QName|SetIntervalTimer|Timer|TypedDictionary)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.utils</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(XML|XMLDocument|XMLList|XMLNode|XMLNodeType|XMLParser|XMLTag)\b</string>
			<key>name</key>
			<string>support.class.haxe.flash9.xml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Array|ArrayAccess|Bool|Class|Date|DateTools|Dynamic|EReg|Enum|Float|Hash|Int|IntHash|IntIter|Iterable|Iterator|Lambda|List|Math|Null|Reflect|Std|String|StringBuf|StringTools|Type|UInt|ValueType|Void|Xml|XmlType)\b</string>
			<key>name</key>
			<string>support.class.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FastCell|FastList|Firebug|Http|Int32|Log|Md5|PosInfos|Public|Resource|Serializer|Stack|StackItem|Template|Timer|TimerQueue|TypeResolver|Unserializer)\b</string>
			<key>name</key>
			<string>support.class.haxe.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Bytes|BytesBuffer|BytesData|BytesInput|BytesOutput|Eof|Error|Input|Output|StringInput)\b</string>
			<key>name</key>
			<string>support.class.haxe.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(AMFConnection|AsyncAdapter|AsyncConnection|AsyncDebugConnection|AsyncProxy|Connection|Context|ContextAll|DelayedConnection|ExternalConnection|FlashJsConnection|HttpAsyncConnection|HttpConnection|LocalConnection|Proxy|Socket|SocketConnection|SocketProtocol|SocketWrapper|SyncSocketConnection)\b</string>
			<key>name</key>
			<string>support.class.haxe.haxe.remoting</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CType|ClassField|Classdef|EnumField|Enumdef|Generic|Infos|Path|PathParams|Platforms|Rights|TypeApi|TypeInfos|TypeParams|TypeRoot|TypeTree|Typedef|XmlParser)\b</string>
			<key>name</key>
			<string>support.class.haxe.haxe.rtti</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(TestCase|TestResult|TestRunner|TestStatus)\b</string>
			<key>name</key>
			<string>support.class.haxe.haxe.unit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Attrib|Check|Fast|Filter|Proxy|Rule)\b</string>
			<key>name</key>
			<string>support.class.haxe.haxe.xml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Anchor|Body|Boot|Button|Checkbox|Document|Dom|Event|FileUpload|Form|FormElement|Frame|Frameset|Hidden|History|HtmlCollection|HtmlDom|IFrame|Image|Lib|Link|Location|MetaDom|Navigator|Option|Password|Radio|Reset|SWFObject|Screen|Select|Selection|Style|StyleSheet|Submit|Text|Textarea|Window|XMLHttpRequest|XMLSocket)\b</string>
			<key>name</key>
			<string>support.class.haxe.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Boot|FileKind|FileStat|FileSystem|Lib|Random|Sys|Utf8|Web)\b</string>
			<key>name</key>
			<string>support.class.haxe.neko</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Connection|Manager|MySql|Object|ResultSet|Sqlite|Transaction)\b</string>
			<key>name</key>
			<string>support.class.haxe.neko.db</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(File|FileHandle|FileInput|FileOutput|FileSeek|Path|Process)\b</string>
			<key>name</key>
			<string>support.class.haxe.neko.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Host|Poll|ProxyDetect|Proxysettings|ServerLoop|Socket|SocketHandle|SocketInput|SocketOutput|ThreadRemotingServer|ThreadServer)\b</string>
			<key>name</key>
			<string>support.class.haxe.neko.net</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Deque|Gc|Loader|LoaderHandle|Lock|Module|ModuleHandle|Mutex|Thread|ThreadHandle|Tls|Ui)\b</string>
			<key>name</key>
			<string>support.class.haxe.neko.vm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CRC32|Compress|Flush|Reader|Uncompress|Writer|ZipEntry)\b</string>
			<key>name</key>
			<string>support.class.haxe.neko.zip</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Boot|CacheLimiter|Exception|FileKind|FileStat|FileSystem|HException|IniHash|Lib|Session|Sys|Utf8|Web)\b</string>
			<key>name</key>
			<string>support.class.haxe.php</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Connection|DBase|Field|FieldType|Manager|Mysql|Object|ResultSet|Sqlite)\b</string>
			<key>name</key>
			<string>support.class.haxe.php.db</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(File|FileHandle|FileInput|FileOutput|FileSeek|Path|Process)\b</string>
			<key>name</key>
			<string>support.class.haxe.php.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Host|Socket|SocketDomain|SocketHandle|SocketInput|SocketOutput|Process)\b</string>
			<key>name</key>
			<string>support.class.haxe.php.net</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(HtmlPrinter|Main)\b</string>
			<key>name</key>
			<string>support.class.haxe.tools.haxedoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Answer|Datas|Developer|Main|Progress|ProgressIn|Project|ProjectInfos|ProjectManager|Remoting_SiteApi|Site|SiteApi|SiteDb|SiteProxy|User|UserInfos|Version|VersionInfos|VersionManager|XmlInfos)\b</string>
			<key>name</key>
			<string>support.class.haxe.tools.haxelib</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Main|Progress)\b</string>
			<key>name</key>
			<string>support.class.haxe.tools.hxinst</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(trace|this|super|untyped)\b</string>
			<key>name</key>
			<string>support.function.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b__(a|arguments__|construct__|dollar__new|js__|keys__|new__|s|typeof__)\b</string>
			<key>name</key>
			<string>support.constant.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(case|cast|catch|default|dynamic|do|else|for|get|if|in|new|set|switch|throw|try|type|while|return|break|continue|extern|dynamic|implements|inline|override|private|public|static|import|using|package|var)\b</string>
			<key>name</key>
			<string>keyword.control.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Bool|Float|String|Void|Dynamic|Int|UInt|T)\b</string>
			<key>name</key>
			<string>storage.type.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(null|true|false)\b</string>
			<key>name</key>
			<string>constant.language.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.haxe</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.haxe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.haxe</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.haxe</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.haxe</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.haxe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.haxe</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.haxe</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.haxe</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.haxe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.haxe</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.haxe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(instanceof|is|typeof)\b</string>
			<key>name</key>
			<string>keyword.operator.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-!%&amp;*+=/?:]</string>
			<key>name</key>
			<string>keyword.operator.symbolic.haxe</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.preprocessor.haxe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[ \t]*(#)[a-zA-Z]+</string>
			<key>name</key>
			<string>meta.preprocessor.haxe</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function)\s+([a-zA-Z_]\w*(?:\w|&gt;|&lt;|,)*)\s*(\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.haxe</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.haxe</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.haxe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.haxe</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.haxe</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^,)\n]+</string>
					<key>name</key>
					<string>variable.parameter.function.haxe</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.haxe</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.haxe</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.haxe</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.haxe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(class|enum|interface)\s+([a-zA-Z_](?:\w|&gt;|&lt;|,)*)(?:\s+(extends|implements)\s+([a-zA-Z_](?:\w|\.)*)\s*,?)*</string>
			<key>name</key>
			<string>meta.class.haxe</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.typedef.haxe</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.haxe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(typedef)\s+([a-zA-Z_]\w*)\s*=</string>
			<key>name</key>
			<string>meta.typedef.haxe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function)\b</string>
			<key>name</key>
			<string>keyword.function.haxe</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.haxe</string>
	<key>uuid</key>
	<string>8620CB7B-D2B6-4A69-8C1A-58E421435C68</string>
</dict>
</plist>
